### ISSUE TITLE
Possible precedence issue with control flow operator

### ISSUE THREAD

**Issue by SilentGene** [bioperl/bioperl-live#272] opened 2018-06-20 15:45 UTC
I used Bio::DB::Fasta in my script.
What does it mean by warning this:
> Possible precedence issue with control flow operator at D:/BioProgram/strawberryperl/perl/site/lib/Bio/DB/IndexedBase.pm line 845.

Yet the outcome looks good.

Bioperl version: 1.007002
System: Windows10

**Comment by jmarshall** [comment] 2018-07-06 09:38
Duplicate of #250. It's asserted there that the warning in this case is benign.

**Comment by bosborne** [comment] 2018-07-17 16:44
Heyu,

I also see this warning in the latest version from CPAN, but do not see the warning in the master branch in Git.

The warning usually means that the code is ambiguous in what it could return, and adding parens to make the precedence perfectly clear is a common fix.

Brian O.

**Comment by carandraug** [comment] 2018-07-17 17:46
Closing since this is already fixed in 6459750c7ea1092 as part of fixing #250

**Closed by carandraug** 2018-07-17 17:46 UTC
