### ISSUE TITLE
Fails if GD.pm is not installed

### ISSUE THREAD

**Issue by andk** [bioperl/bioperl-live#326] opened 2019-09-26 04:24 UTC
Sample fail report: http://www.cpantesters.org/cpan/report/107056414

Looks like either a dependency needs to be declared or a test rewritten.

**Comment by carandraug** [comment] 2019-09-26 10:07
Thank you for the bug report. This is already fixed (duplicate of issue #323) we just need to make a new release. But we are having some issues with permissions in PAUSE (see andk/pause#344) and need them sorted first.

**Closed by carandraug** 2019-09-26 10:07 UTC
